# Generated by Django 5.1.6 on 2025-03-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_images_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetwork',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='status',
            field=models.CharField(default='Not Trained', max_length=20),
        ),
    ]
