# Generated by Django 5.1.6 on 2025-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_neuralnetwork_accuracy_neuralnetwork_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetwork',
            name='name',
            field=models.CharField(default='UserModel', max_length=255, unique=True),
        ),
    ]
